"""Object storage for logos (Phase 3d).

The directive is explicit: "Local disk storage must not survive this
refactor." So S3-compatible object storage is the system of record and
there is no silent local fallback:

  * S3_BUCKET unset  -> StorageNotConfigured, and the caller gets a clear
    503 telling the operator to configure object storage. Logos are never
    quietly written to a container's ephemeral disk.
  * S3 call fails    -> StorageUnavailable, also a 503. Losing a logo is
    visible; silently keeping it on local disk is how multi-instance
    deployments end up with images that only exist on one box.
  * ALLOW_LOCAL_STORAGE=1 is an explicit, opt-in dev/test escape hatch
    that keeps a single-process developer loop working. It is off by
    default and never used implicitly.

S3-compatible: AWS S3, Cloudflare R2, and Backblaze B2 all work via
S3_ENDPOINT_URL. The DB stores an "s3://bucket/key" URI.

References are self-describing, so a row written while local mode was
explicitly enabled is still readable in that mode.
"""
import io
import logging
import os
import secrets

logger = logging.getLogger("nare")

APP_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCAL_DIR = os.path.join(APP_DIR, "uploads")
S3_PREFIX = "s3://"
_store = None


class StorageNotConfigured(RuntimeError):
    """No S3 bucket configured and local storage not explicitly allowed."""


class StorageUnavailable(RuntimeError):
    """Object storage is configured but the call failed."""


def s3_configured() -> bool:
    return bool(os.getenv("S3_BUCKET", "").strip())


def local_allowed() -> bool:
    """Local disk is opt-in only, for dev/test. Never the default."""
    return os.getenv("ALLOW_LOCAL_STORAGE", "").strip().lower() in ("1", "true", "yes", "on")


def _local_path(key: str) -> str:
    os.makedirs(LOCAL_DIR, exist_ok=True)
    # key is generated by us (hex + sanitized extension) — never user input
    return os.path.join(LOCAL_DIR, os.path.basename(key))


class LocalLogoStore:
    """Dev/test only. Requires ALLOW_LOCAL_STORAGE=1 to be selected."""

    name = "local"

    def save(self, key: str, data: bytes) -> str:
        path = _local_path(key)
        with open(path, "wb") as fh:
            fh.write(data)
        return path

    def load(self, ref: str) -> bytes:
        with open(ref, "rb") as fh:
            return fh.read()

    def delete(self, ref: str) -> None:
        try:
            os.remove(ref)
        except FileNotFoundError:
            pass


class S3LogoStore:
    name = "s3"

    def __init__(self, bucket, endpoint=None, region=None):
        import boto3
        from botocore.config import Config

        self.bucket = bucket
        self.client = boto3.client(
            "s3",
            endpoint_url=endpoint or None,
            region_name=region or os.getenv("AWS_REGION", "us-east-1"),
            config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
        )

    def _key(self, ref: str) -> str:
        rest = ref[len(S3_PREFIX):]
        if rest.startswith(self.bucket + "/"):
            return rest[len(self.bucket) + 1:]
        return rest

    def save(self, key: str, data: bytes) -> str:
        try:
            self.client.put_object(Bucket=self.bucket, Key=key, Body=data)
            return f"{S3_PREFIX}{self.bucket}/{key}"
        except Exception as e:
            logger.error("S3 put_object failed for bucket %s: %s", self.bucket, e)
            raise StorageUnavailable(f"object storage write failed: {e}") from e

    def load(self, ref: str) -> bytes:
        try:
            obj = self.client.get_object(Bucket=self.bucket, Key=self._key(ref))
            return obj["Body"].read()
        except Exception as e:
            logger.error("S3 get_object failed for %s: %s", ref, e)
            raise StorageUnavailable(f"object storage read failed: {e}") from e

    def delete(self, ref: str) -> None:
        try:
            self.client.delete_object(Bucket=self.bucket, Key=self._key(ref))
        except Exception as e:
            logger.error("S3 delete_object failed for %s: %s", ref, e)
            raise StorageUnavailable(f"object storage delete failed: {e}") from e


def get_store():
    """The configured store. S3 unless local was explicitly allowed."""
    global _store
    if _store is not None:
        return _store
    if s3_configured():
        try:
            _store = S3LogoStore(
                bucket=os.getenv("S3_BUCKET", "").strip(),
                endpoint=os.getenv("S3_ENDPOINT_URL", "").strip() or None,
                region=os.getenv("AWS_REGION", "").strip() or None,
            )
            logger.info("Logo storage: S3 bucket %s", _store.bucket)
            return _store
        except Exception as e:
            raise StorageNotConfigured(
                f"S3_BUCKET is set but the client could not be created ({e}); "
                "check AWS credentials and S3_ENDPOINT_URL"
            ) from e
    if local_allowed():
        logger.warning(
            "Logo storage: LOCAL DISK (ALLOW_LOCAL_STORAGE=1). Not for "
            "production — containers have ephemeral filesystems."
        )
        _store = LocalLogoStore()
        return _store
    raise StorageNotConfigured(
        "object storage is not configured: set S3_BUCKET (plus "
        "S3_ENDPOINT_URL for R2/B2), or set ALLOW_LOCAL_STORAGE=1 to run a "
        "single-process dev environment"
    )


def reset_state():
    global _store
    _store = None


def new_key(ext=".png") -> str:
    return f"{secrets.token_hex(12)}{ext}"


def save_logo(data: bytes, ext=".png") -> str:
    return get_store().save(new_key(ext), data)


def load_logo(ref: str) -> bytes:
    """Read a stored logo. Understands both s3:// refs and local paths."""
    if ref.startswith(S3_PREFIX):
        return get_store().load(ref)
    # A non-s3 ref is a legacy/local path: only readable in explicit local mode.
    if not local_allowed():
        raise StorageNotConfigured(
            f"stored logo {ref!r} predates object storage and needs "
            "ALLOW_LOCAL_STORAGE=1 to be migrated"
        )
    return LocalLogoStore().load(ref)


def load_logo_image(ref: str):
    """PIL Image for rendering, or None when unreadable."""
    from PIL import Image

    try:
        return Image.open(io.BytesIO(load_logo(ref))).convert("RGBA")
    except Exception as e:
        logger.warning("logo image decode failed for %s: %s", ref, e)
        return None
