"""Object storage for logos (Phase 3d).

Local disk is no longer the system of record once S3 is configured: with
S3_BUCKET set, bytes go to any S3-compatible service (AWS S3, Cloudflare
R2, Backblaze B2 via S3_ENDPOINT_URL) and the DB stores an "s3://" URI.
Without S3_BUCKET the store is the local uploads/ dir, so a fresh clone
still works with zero infrastructure.

Safety properties:
  * References are self-describing ("s3://bucket/key" vs an absolute
    path), so rows written before the switch keep working.
  * S3 errors never 500 a request: they log and fall back to local, which
    is the only place disk is still written.
  * load() returns bytes so the renderer never needs a filesystem path.
"""
import io
import logging
import os
import secrets

logger = logging.getLogger("nare")

APP_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCAL_DIR = os.path.join(APP_DIR, "uploads")
S3_PREFIX = "s3://"
_store = None


def s3_configured() -> bool:
    return bool(os.getenv("S3_BUCKET", "").strip())


def _local_path(key: str) -> str:
    os.makedirs(LOCAL_DIR, exist_ok=True)
    # key is generated by us (hex + sanitized extension) — never user input
    return os.path.join(LOCAL_DIR, os.path.basename(key))


class LocalLogoStore:
    name = "local"

    def save(self, key: str, data: bytes) -> str:
        path = _local_path(key)
        with open(path, "wb") as fh:
            fh.write(data)
        return path

    def load(self, ref: str) -> bytes:
        with open(ref, "rb") as fh:
            return fh.read()

    def delete(self, ref: str) -> None:
        try:
            os.remove(ref)
        except FileNotFoundError:
            pass


class S3LogoStore:
    name = "s3"

    def __init__(self, bucket, endpoint=None, region=None):
        import boto3
        from botocore.config import Config

        self.bucket = bucket
        self.client = boto3.client(
            "s3",
            endpoint_url=endpoint or None,
            region_name=region or os.getenv("AWS_REGION", "us-east-1"),
            config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
        )

    def _key(self, ref: str) -> str:
        rest = ref[len(S3_PREFIX):]
        if rest.startswith(self.bucket + "/"):
            return rest[len(self.bucket) + 1:]
        return rest

    def save(self, key: str, data: bytes) -> str:
        try:
            self.client.put_object(Bucket=self.bucket, Key=key, Body=data)
            return f"{S3_PREFIX}{self.bucket}/{key}"
        except Exception as e:
            # Never fail the request: degrade to local, keep the reference valid
            logger.warning(f"S3 put_object failed ({e}); storing locally instead")
            return LocalLogoStore().save(key, data)

    def load(self, ref: str) -> bytes:
        try:
            obj = self.client.get_object(Bucket=self.bucket, Key=self._key(ref))
            return obj["Body"].read()
        except Exception as e:
            logger.warning(f"S3 get_object failed ({e}); trying local copy")
            return LocalLogoStore().load(ref)

    def delete(self, ref: str) -> None:
        try:
            self.client.delete_object(Bucket=self.bucket, Key=self._key(ref))
        except Exception as e:
            logger.warning(f"S3 delete_object failed: {e}")


def get_store():
    """Configured store (S3 when S3_BUCKET is set, else local). Cached."""
    global _store
    if _store is not None:
        return _store
    if s3_configured():
        try:
            _store = S3LogoStore(
                bucket=os.getenv("S3_BUCKET", "").strip(),
                endpoint=os.getenv("S3_ENDPOINT_URL", "").strip() or None,
                region=os.getenv("AWS_REGION", "").strip() or None,
            )
            logger.info("Logo storage: S3 bucket %s", _store.bucket)
            return _store
        except Exception as e:
            logger.warning(f"S3 unavailable ({e}); falling back to local disk")
    _store = LocalLogoStore()
    return _store


def reset_state():
    global _store
    _store = None


def new_key(ext=".png") -> str:
    return f"{secrets.token_hex(12)}{ext}"


def save_logo(data: bytes, ext=".png") -> str:
    return get_store().save(new_key(ext), data)


def load_logo(ref: str) -> bytes:
    """Read a stored logo. Understands both s3:// refs and local paths."""
    if ref.startswith(S3_PREFIX):
        return get_store().load(ref)
    return LocalLogoStore().load(ref)


def load_logo_image(ref: str):
    """PIL Image for rendering, or None when unreadable."""
    from PIL import Image

    try:
        return Image.open(io.BytesIO(load_logo(ref))).convert("RGBA")
    except Exception as e:
        logger.warning(f"Logo load failed for {ref}: {e}")
        return None
